apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 8082 ## ClusterIP port
      targetPort: 80 ## ContainerIP port
      nodePort: 30000 ## External access port

